### PR TITLE
Made code more IDE friendly and removed global.

### PR DESCRIPTION
**Pull request by mhrmm**
@3141592654  Created a factory method to eliminate the use of global variables. Also, made some modifications to make IDEs generate fewer warnings.

### CODE REVIEW

**Comment by mhrmm** [comment]
Before signing off on this, make sure to check out the PR and ensure that it has the same behavior as your current code.

**Comment by 3141592654** [comment]
Indentation of code looks good.

Not totally convinced on game_factory? It's true it removes Env and preprocess_observation from the global namespace. But it adds BasicGameFactory, SmogonGameFactory and factory to the global namespace, and in that sense makes the problem worse. One alternative would be to create a gym_interface and give it a make method that accepts "Pokemon" and "Pokemon-Online", which is what gym does in pg-pong.

Also not convinced importing game_model as gm is better than from game_model import *. The idea is that everything in game_model is unchanging and infallible. (Now that I think of it, renaming it to CONSTANTS.py would be a good idea). And things that are unchanging and infallible belong in the global namespace.

**Comment by mhrmm** [comment]
Importing game_model as gm is a compromise to avoid lots of IDE warnings
that result from a

from game_model import *

statement. Alternatively you can just import them all by name, but that's
more difficult to maintain.

As far as game_factory, I'd argue that anything is better than resorting to
the global keyword.

Mark

**Comment by 3141592654** [comment]
What are the warnings? They might or might not be relevant to importing a bunch of constants. (It might be nicer to make game_model into a JSON file, but I'm not sure how that squares with NUM_WEATHER = len(WEATHER_DICT)).
Also, what IDE are you using?

Regarding the global keyword, that is used in bookkeeper.py, which is not in game_factory. Using self.preprocess_observation instead of global preprocess_observation seems like a good idea.

**Comment by 3141592654** [comment]
Some ideas implemented into other pull request, as discussed last Monday.

**Pull request closed without merging**
